### PR TITLE
Fixes for rsync/mariabackup SST

### PR DESCRIPTION
**Pull request by mkaruza**
* Donor node will now provide log-bin-index argument to wsrep_sst_rsync script
* Write correct path and log-bin file names into joiner log-bin-index file
* Extend archive timestamp in mariabackup script

### CODE REVIEW

**Comment by mkaruza** [comment]
Test jenkins run: https://jenkins.galeracluster.com:8443/job/mtr-galera-4.x-mariadb-10.4/477/consoleFull

**Comment by mkaruza** [comment]
test_pr

**Comment by temeo** [comment]
https://jenkins.galeracluster.com:8443/job/mtr-galera-4.x-mariadb-10.4/493/consoleFull
Test galera_gcache_recover_manytrx is now passing and could be recorded:
```
CURRENT_TEST: galera.galera_gcache_recover_manytrx
--- /home/jenkins/workspace/mtr-galera-4.x-mariadb-10.4/mysql-wsrep/mysql-test/suite/galera/r/galera_gcache_recover_manytrx.result	2019-02-08 10:22:01.365544962 +0100
+++ /home/jenkins/workspace/mtr-galera-4.x-mariadb-10.4/mysql-wsrep/mysql-test/suite/galera/r/galera_gcache_recover_manytrx.reject	2019-02-08 10:36:29.151973076 +0100
@@ -1,3 +1,5 @@
+connection node_2;
+connection node_1;
 SET SESSION wsrep_sync_wait = 0;
 CREATE TABLE t1 (f1 INTEGER PRIMARY KEY AUTO_INCREMENT, f2 LONGBLOB) ENGINE=InnoDB;
 CREATE TABLE ten (f1 INTEGER) ENGINE=InnoDB;

mysqltest: Result length mismatch

```

**Comment by mkaruza** [comment]
Opened PR in mariadb, https://github.com/MariaDB/server/pull/1170.
Closing this PR.

**Pull request closed without merging**
