### PR TITLE
MDEV-20008: Galera strict mode

### PR DESCRIPTION
**Pull request by mkaruza**
Added new enum variable `wsrep_mode` which can be used to turn on WSREP
features which are not part of default behaviour.
Added enum `STRICT` to enable strict mode behaviour.

### CODE REVIEW

**Comment by sjaakola** [comment]
MDEV-20008 suggests to have individual "flags" for rejecting each possibly vulnerable actions. So we need to figure out good names for these already developed rejections. It is ok to have wsrep_mode=STRICT, but this should work as aggregation of all defined wsrep_mode flags. 
e.g. following flags could be used:
INNODB_ONLY - allow writes only for innodb tables (except in mysql schema, which can be myisam or aria)
BINLOG_FORMAT_ROW_ONLY - reject STATEMENT or MIXED format
REQUIRE_PRIMARY_KEY - accept onl tables with primary key defined

Then STRICT works as: INNODB_ONLY | BINLOG_FORMAT_ONLY | REQUIRE_PRIMARY_KEY

**Comment by sjaakola** [comment]
This PR is good in current form. 
However, as it removes one configuration variable wsrep_strict_ddl, it is somewhat questionable if we can do this without first declaring wsrep_strict_ddl as deprecated, and drop the variable only after deprecation period has elapsed.
But, I would leave this for MariaDB side review to decide about.

**Review by sjaakola — APPROVED** [review]
This is good to submit for MariaDB side review. Dropping wsrep_strict_ddl variable may require deprecation process.

**Comment by mkaruza** [comment]
Opened PR against MariaDB

**Pull request closed without merging**
