### PR TITLE
Always call wsrep_deinit_server() in unireg_abort() if wsrep is on

### PR DESCRIPTION
**Pull request by temeo**
Missing call to wsrep_deinit_server() will leak memory.

### CODE REVIEW

**Comment by temeo** [comment]
https://jenkins.galeracluster.com:8443/job/mtr-galera-4.x-mariadb-10.4/204/

**Comment by sjaakola** [comment]
Is this rebased with bb-10.4-galera4? This may be overlapping with Bar review fixes already merged in: https://github.com/codership/mariadb-server/pull/17/commits/8f3b2a77f7e0d83d06eabaf3e6d7ae8696852adc

**Comment by temeo** [comment]
This was rebased earlier on, but now my local working copy and this PR have diverged. Will need to rebase and test again.

**Comment by temeo** [comment]
Native test `perfschema.bad_option_4` fails due to changes in this PR.

**Comment by temeo** [comment]
No regressions in native suites anymore, will close and submit to MariaDB.

**Pull request closed without merging**
